name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.2.1
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - plotly==5.9.0
  - pillow=10.0.1
  - mlflow=2.7.1
  - pip:
      - wandb==0.15.12
      - omegaconf==2.0.6