name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=23.2.1
  - mlflow=2.7.1
  - hydra-core=1.0.6
  - pytest=6.2.2
  - pip:
      - wandb==0.15.12
      - hydra-joblib-launcher==1.1.2
